//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUsers()
        {
            this.AppTokens = new HashSet<AppTokens>();
        }
    
        public long Id { get; set; }
        public long StateId { get; set; }
        public string FbId { get; set; }
        public int Audience { get; set; }
        public int IsInterested { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string LastNames { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Extension { get; set; }
        public int ChildrenCount { get; set; }
        public int LocationCount { get; set; }
        public Nullable<System.DateTime> LockedAt { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAviso { get; set; }
        public Nullable<bool> EsTitular { get; set; }
        public Nullable<int> IsBlocked { get; set; }
        public Nullable<int> ChildrenCount05x { get; set; }
        public Nullable<int> ChildrenCount68x { get; set; }
        public Nullable<int> ChildrenCount912x { get; set; }
        public Nullable<int> ChildrenCount12xx { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppTokens> AppTokens { get; set; }
        public virtual States States { get; set; }
    }
}
