//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public long Id { get; set; }
        public Nullable<int> SigninRequired { get; set; }
        public int Audience { get; set; }
        public long CategoryId { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public string ThumbExtension { get; set; }
        public string SmallThumbExtension { get; set; }
        public System.DateTime PublishedAt { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Published { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
